FROM archlinux

RUN pacman -Syy --noconfirm ca-certificates firefox && \
    pacman -Scc --noconfirm && \
    rm -rf /var/cache/pacman/pkg/

RUN groupadd --gid 1000 app && \
    useradd --no-log-init --system --uid 1000 -g 1000 -G users --home-dir /home --shell /bin/bash app && \
    usermod -a -G audio app && \
    usermod -a -G video app

WORKDIR /home
RUN chown -R app:app /home /dev/stdout /dev/stderr
USER app

ENTRYPOINT ["firefox", "--no-remote", "--setDefaultBrowser"]
