FROM archlinux

RUN echo '[multilib]' >> /etc/pacman.conf && \
    echo 'Include = /etc/pacman.d/mirrorlist' >> /etc/pacman.conf && \
    pacman --noconfirm -Syyu && \
    pacman --noconfirm -S base-devel git && \
    useradd --no-log-init --system -G users --home-dir /home -s /bin/bash aur && \
    passwd -d aur && \
    echo 'aur ALL=(ALL) ALL' > /etc/sudoers.d/aur && \
    mkdir -p /home/.gnupg && \
    echo 'standard-resolver' > /home/.gnupg/dirmngr.conf && \
    chown -R aur:users /home && \
    mkdir /build && \
    chown -R aur:users /build && \
    cd /build && \
    sudo -u aur git clone --depth 1 https://aur.archlinux.org/yay.git && \
    cd yay && \
    sudo -u aur makepkg --noconfirm -si && \
    sudo -u aur yay --afterclean --removemake --save && \
    cd /home && \
    pacman -Qtdq | xargs -r pacman --noconfirm -Rcns && \
    rm -rf /home/.cache && \
    rm -rf /build

RUN pacman -Sy --noconfirm ca-certificates ttf-dejavu noto-fonts-emoji ttf-joypixels && \
    sudo -u aur yay --noconfirm -Sy ttf-symbola brave-beta-bin && \
    sudo -u aur yay --noconfirm -Scc && \
    rm -rf /var/cache/pacman/pkg/

WORKDIR /home
RUN useradd --no-log-init --system -U -G aur,users,audio,video --home-dir /home -s /bin/bash app && \
    chown -R app:users /home /dev/stdout /dev/stderr

USER app
# https://developer.chrome.com/blog/browser-flags
# https://wiki.archlinux.org/title/Chromium
ENTRYPOINT ["brave-browser-beta", \
            "--disable-breakpad", \
            "--disable-bundled-ppapi-flash", \
            "--disable-crash-reporter", \
            "--disable-demo-mode", \
            "--disable-dev-shm-usage", \
            "--disable-notifications", \
            "--disable-speech-api", \
            "--enable-zero-copy", \
            "--ignore-gpu-blocklist", \
            "--process-per-site", \
            "--start-maximized"]
