FROM ubuntu

RUN apt-get update -y && \
    apt-get install -y --no-install-recommends ca-certificates firefox && \
    rm -rf /var/lib/apt/lists

WORKDIR /home
RUN useradd --no-log-init --system -U -G users,audio,video --home-dir /home --shell /bin/bash app && \
    chown -R app:app /home /dev/stdout /dev/stderr

USER app
ENTRYPOINT ["firefox", "--no-remote", "--setDefaultBrowser"]
