FROM archlinux

RUN pacman -Syyu --noconfirm ca-certificates ttf-joypixels firefox && \
    pacman -Scc --noconfirm && \
    rm -rf /var/cache/pacman/pkg/

WORKDIR /home
RUN useradd --no-log-init --system -U -G users,audio,video --home-dir /home -s /bin/bash app && \
    chown -R app:users /home /dev/stdout /dev/stderr

USER app
ENTRYPOINT ["firefox", "--no-remote", "--setDefaultBrowser"]
