FROM archlinux

RUN pacman -Syyu --noconfirm ttf-dejavu noto-fonts-emoji ttf-joypixels pipewire chromium && \
    pacman -Scc --noconfirm && \
    rm -rf /var/cache/pacman/pkg/

WORKDIR /home
RUN useradd --no-log-init --system -U -G users,audio,video --home-dir /home -s /bin/bash app && \
    chown -R app:users /home /dev/stdout /dev/stderr

USER app
# https://developer.chrome.com/blog/browser-flags
# https://wiki.archlinux.org/title/Chromium
ENTRYPOINT ["chromium", \
            "--disable-breakpad", \
            "--disable-bundled-ppapi-flash", \
            "--disable-crash-reporter", \
            "--disable-demo-mode", \
            "--disable-dev-shm-usage", \
            "--disable-notifications", \
            "--disable-speech-api", \
            "--enable-zero-copy", \
            "--ignore-gpu-blocklist", \
            "--process-per-site", \
            "--start-maximized"]
