FROM fedora

RUN dnf -y update && \
    dnf -y install ca-certificates firefox && \
    dnf clean all

WORKDIR /home
RUN useradd --no-log-init --system -U -G users,audio,video --home-dir /home -s /bin/bash app && \
    chown -R app:users /home /dev/stdout /dev/stderr

USER app
ENTRYPOINT ["firefox", "--no-remote", "--setDefaultBrowser"]
